# Generated by Django 3.2.6 on 2021-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_vote_ration_project_vote_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feaured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
